openmrs/openmrs-module-htmlformentry

omod/src/main/java/org/openmrs/module/htmlformentry/web/controller/HtmlFormFromFileController.java

Macros are not evaluated on "Preview Form From File" page - HTML-185

Macros are not evaluated on "Preview Form From File" page - HTML-185

---

omod/src/main/webapp/resources/htmlFormEntry.js

modified:   omod/src/main/webapp/resources/htmlFormEntry.js
related to https://issues.openmrs.org/browse/HTML-607

HTML-607: Adding support of the '.change()' event for autocomplete fields

---

api/src/main/java/org/openmrs/module/htmlformentry/CustomFormSubmissionAction.java
api/src/main/java/org/openmrs/module/htmlformentry/FormEntryContext.java
api/src/main/java/org/openmrs/module/htmlformentry/FormEntrySession.java
api/src/main/java/org/openmrs/module/htmlformentry/FormSubmissionController.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryGenerator.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryGlobalProperties.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormExporter.java
api/src/main/java/org/openmrs/module/htmlformentry/VelocityFunctions.java

Changed grammar & spelling

---

README.md

[Google Code In 2015] Improved README text

---

api/src/main/java/org/openmrs/module/htmlformentry/element/PatientDetailSubmissionElement.java

with exceptions that was causing it to fail saving

HTML-624 Null point exception shown for patient Identifier type when not required in HTML form

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/ObsAnswerLocationTagsTest.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java

Please refer to the description in [https://issues.openmrs.org/browse/HTML-631](https://issues.openmrs.org/browse/HTML-631)

HTML-631 Handle empty or null LocationTag gracefully

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/widget/AutocompleteWidgetTest.java
api-tests/src/test/java/org/openmrs/module/htmlformentry/widget/DateWidgetTest.java
api-tests/src/test/java/org/openmrs/module/htmlformentry/widget/LocationWidgetTest.java
api-tests/src/test/java/org/openmrs/module/htmlformentry/widget/RadioButtonsWidgetTest.java

Please refer to [https://issues.openmrs.org/browse/HTML-633?jql=project%20%3D%20HTML](https://issues.openmrs.org/browse/HTML-633?jql=project%20%3D%20HTML)

HTML-633 Added tests for widgets

---

omod/src/main/webapp/resources/htmlFormEntry.js

Able to get value from ".5"
https://issues.openmrs.org/browse/HTML-474

Cannot enter a precise number starting with a decimal

---

api/src/test/java/org/openmrs/module/htmlformentry/widget/CheckboxWidgetTest.java
api/src/test/java/org/openmrs/module/htmlformentry/widget/DateWidgetTest.java
api/src/test/java/org/openmrs/module/htmlformentry/widget/DropdownWidgetTest.java
api/src/test/java/org/openmrs/module/htmlformentry/widget/PersonNameWidgetTest.java
api/src/test/java/org/openmrs/module/htmlformentry/widget/UploadWidgetTest.java

I added some widget tests to improve more test coverages (line coverage)
- checkboxWidget: 0% -> 76%
- dateWidget: 26% -> 36%
- personNameWidget: 0% -> 64%
- uploadWidget: 0% -> 35%
- dropdownWidget: 0% -> 51%

added widget tests for more test coverages

---

api/src/test/java/org/openmrs/module/htmlformentry/FormEntryContextTest.java

https://issues.openmrs.org/browse/HTML-635

Added tests for FormEntryContext class

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/action/RepeatControllerActionTest.java

https://issues.openmrs.org/browse/HTML-638

HTML-638 Added tests for RepeatControllerAction

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/element/ObsSubmissionElementTest.java

https://issues.openmrs.org/browse/HTML-637

HTML-637 Added tests for ObsSubmissionElement

---

api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryActivator.java

https://issues.openmrs.org/browse/HTML-646

HTML-646 followup: stop htmlformentry19

---

.tx/config
api/src/main/resources/messages_ar.properties
api/src/main/resources/messages_el.properties
api/src/main/resources/messages_fa.properties
api/src/main/resources/messages_hi.properties
api/src/main/resources/messages_hy.properties
api/src/main/resources/messages_id_ID.properties
api/src/main/resources/messages_it.properties
api/src/main/resources/messages_ku.properties
api/src/main/resources/messages_lt.properties
api/src/main/resources/messages_pl.properties
api/src/main/resources/messages_ru.properties
api/src/main/resources/messages_si.properties
api/src/main/resources/messages_sw.properties
api/src/main/resources/messages_te.properties
omod/src/main/resources/config.xml

Issue: https://issues.openmrs.org/browse/RA-1001

RA-1001: Update all modules that use Transifex to support all languages we support 

---

omod/pom.xml
omod/src/main/webapp/resources/htmlFormEntry.js
omod/src/test/java/org/openmrs/htmlformentry/web/controller/HtmlFormAjaxValidationControllerTest.java
pom.xml

@dkayiwa I am running into trouble with the unit tests do advise

HTML-262 Fixing the disallow duplicate encounter submission tag Javascript tag

---

api/src/main/java/org/openmrs/module/htmlformentry/widget/NumberFieldWidget.java
api/src/main/resources/messages.properties
api/src/main/resources/messages_ar.properties
api/src/main/resources/messages_de.properties
api/src/main/resources/messages_el.properties
api/src/main/resources/messages_es.properties
api/src/main/resources/messages_fa.properties
api/src/main/resources/messages_fr.properties
api/src/main/resources/messages_hi.properties
api/src/main/resources/messages_ht.properties
api/src/main/resources/messages_hy.properties
api/src/main/resources/messages_id_ID.properties
api/src/main/resources/messages_it.properties
api/src/main/resources/messages_ku.properties
api/src/main/resources/messages_lt.properties
api/src/main/resources/messages_pl.properties
api/src/main/resources/messages_pt.properties
api/src/main/resources/messages_ru.properties
api/src/main/resources/messages_si.properties
api/src/main/resources/messages_sw.properties
api/src/main/resources/messages_te.properties

fixed the issue : https://issues.openmrs.org/browse/HTML-570

fixed HTML-570

---

omod/src/main/webapp/resources/htmlFormEntry.js

fixed issue https://issues.openmrs.org/browse/HTML-573

fixed HTML-573

---

api/src/main/java/org/openmrs/module/htmlformentry/element/EncounterDetailSubmissionElement.java
api/src/main/java/org/openmrs/module/htmlformentry/widget/TimeWidget.java

Added "hideSeconds" attribute to <obs>

HTML-612 Add "hideSeconds" attribute to <obs>

---

api/src/main/java/org/openmrs/module/htmlformentry/element/DrugOrderSubmissionElement.java

Modified DrugOrderSubmissionElement.java accordingly

HTML- 329  add a drugOrder attribute to hide only dose, not frequency

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/handler/ObsTagHandlerTest.java
api/src/main/java/org/openmrs/module/htmlformentry/handler/ObsTagHandler.java
api/src/main/resources/messages.properties

https://issues.openmrs.org/browse/HTML-366

HTML-366 Form Schema Preview should show a warning if an answer is not legal for its question

---

api/src/main/java/org/openmrs/module/htmlformentry/element/ObsSubmissionElement.java

Issue Url - https://issues.openmrs.org/browse/HTML-612
hideSeconds attribute was implemented in the <encounterDate> tag earlier by me.
modified the ObsSubmissionElement to check for hideSeconds attribute in <obs>

HTML-612-2 Add "hideSeconds" attribute to <obs>

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtilTest.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java

Disallow malicious xxe, allow benign xxe

Configure xml parser to ignore xxe entities

---

.github/PULL_REQUEST_TEMPLATE.md

Proposed a Pull Request Format similar to openmrs-core one.
[see](https://issues.openmrs.org/browse/HTML-679)

HTML-679 Adding a PR template to this repository

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/ObsTagTest.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java
api/src/main/java/org/openmrs/module/htmlformentry/element/ObsSubmissionElement.java
api/src/test/resources/org/openmrs/module/htmlformentry/include/RegressionTest-data-openmrs-1.9.xml
api/src/test/resources/org/openmrs/module/htmlformentry/include/obsDrugForm.xml

HTML-683, add support for drug checkbox via answerDrugId attribute

---

api/src/main/java/org/openmrs/module/htmlformentry/element/ObsSubmissionElement.java

HTML-683, when answerDrugId parameter is present search for Drugs

---

api/src/main/java/org/openmrs/module/htmlformentry/element/EnrollInProgramElement.java

https://issues.openmrs.org/browse/HTML-690
Now that the enrollInProgram tag can create a checkbox that will conditionally enroll a patient, it would be great if that checkbox could toggle whether to show or hide a section, like the Obs checkboxes.

HTML-690 enrollInProgram tag checkbox should be able to toggle show/hide elements

---

api-2.2/pom.xml
api-2.2/src/main/java/org/openmrs/module/htmlformentry/ConditionElement.java
api-2.2/src/main/java/org/openmrs/module/htmlformentry/handler/ConditionTagHandlerSupport2_2.java
api/src/main/java/org/openmrs/module/htmlformentry/handler/ConditionTagHandler.java
api/src/main/java/org/openmrs/module/htmlformentry/handler/ConditionTagHandlerSupport.java
api/src/main/java/org/openmrs/module/htmlformentry/handler/ConditionTagHandlerSupport1_10.java
api/src/main/resources/messages.properties
api/src/main/resources/moduleApplicationContext.xml
omod/pom.xml
pom.xml

Ticket : https://issues.openmrs.org/browse/HTML-705

HTML-705: HTML Form Entry tag for creating a single condition

---

api-2.2/src/main/java/org/openmrs/module/htmlformentry/ConditionElement.java
api-2.2/src/test/java/org/openmrs/htmlformentry/element/ConditionElementTest.java

Followup commit on => https://issues.openmrs.org/browse/HTML-705

HTML-705: Handling cases were a Condition was not provided

---

README.md

Fixed syntax issue on paragraph 32
No? Unsure? -> execute command `git pull …

Syntax issue on paragraph 32

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/ModifyObsTest.java
api/src/main/java/org/openmrs/module/htmlformentry/FormSubmissionActions.java
api/src/test/java/org/openmrs/module/htmlformentry/RegressionTestHelper.java

HTML-675 obs table previous_version column not filled in edit mode
added call to setPreviousVersion() on new Obs to be created in modifyObs referencing obs that is to be voided.
If I should remove the "noisy" changed lines I discuss in the following statements (due to changes from the formatter), please let me know.
A number of "changed" lines are due to application of the openmrs code formatter xml rules via eclipse ctrl+shift+f (this xml version is a few commits back from master head (commit https://github.com/openmrs/openmrs-core/commit/119013248dda3876d58e7dbaf48258c20f548c67) so let me know if there's an issue with that). 
GitHub "Hide whitespace changes" will help cut down on the edited lines, but some were changed to wrap line length. Let me know if there appears to be any errors …

HTML-675: adding setPreviousVersion() call in FormSubmissionAction of modifyObs

---

api-2.2/src/main/java/org/openmrs/module/htmlformentry/handler/ConditionTagHandlerSupport2_2.java
omod/src/main/resources/config.xml

see https://issues.openmrs.org/browse/HTML-707

HTML-707 Update ConditionTagHandlerSupport2_2 to work for later versions

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/HtmlFormEntryGeneratorTest.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryGenerator.java

https://issues.openmrs.org/browse/HTML-26
Supplement PR to https://github.com/openmrs/openmrs-module-htmlformentry/pull/162
Enabled style sheet to be run at the start and end of the page
Added unit tests 
Modified new JQuery reference to prevent conflict

HTML-26: Allow HTML Forms to be split into pages

---

api-2.0/src/main/java/org/openmrs/module/htmlformentry/DrugCompatibility2_0.java
api/src/main/java/org/openmrs/module/htmlformentry/widget/Option.java
api/src/main/java/org/openmrs/module/htmlformentry/widget/RemoteJsonAutocompleteWidget.java
omod/src/main/java/org/openmrs/module/htmlformentry/web/controller/HtmlFormSearchController.java

HTML-718, display retired drugs as greyed-out options

---

api/src/main/java/org/openmrs/module/htmlformentry/FormEntrySession.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlForm.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryGenerator.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryService.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormValidator.java
api/src/main/java/org/openmrs/module/htmlformentry/VelocityFunctions.java
api/src/main/java/org/openmrs/module/htmlformentry/element/DrugOrderSubmissionElement.java
api/src/main/java/org/openmrs/module/htmlformentry/element/EncounterDetailSubmissionElement.java
api/src/main/java/org/openmrs/module/htmlformentry/element/ExitFromCareSubmissionElement.java
api/src/main/java/org/openmrs/module/htmlformentry/element/RelationshipSubmissionElement.java
api/src/main/java/org/openmrs/module/htmlformentry/handler/LogicConditionalIncludeTagHandler.java
api/src/main/java/org/openmrs/module/htmlformentry/widget/AutocompleteWidget.java

Replaced all instances of @should in HTML Form Entry Module
see https://issues.openmrs.org/browse/TRUNK-5709
No? …

TRUNK-5709:Replaced all instances of @should in HTML Form Entry Module

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/WorkflowStateTagTest.java
api/src/main/java/org/openmrs/module/htmlformentry/FormEntrySession.java
api/src/main/java/org/openmrs/module/htmlformentry/FormSubmissionActions.java

update patient program enrollment date if the state startDate is before the current PatientProgram dateEnrolled
HTML-721 Retroactively adding a state to a patient program before the current enrollment date should update the PatientProgram enrollment Date
When a program workflow state is retroactively entered for an encounterDatetime before the enrollment of the existing program, and a new program workflow state is entered, the enrollment date is updated on a new copy, and the original PatientProgram is voided to leave an audit trail.
Additional assertions were added in the existing unit tests where this was observed. 
see https://issues.openmrs.org/browse/HTML-721
this is a prereq for https://issues.openmrs.org/browse/HTML-720
No? -> …

HTML-721 : retroactive entry updates patient program enrollment date

---

api/src/main/java/org/openmrs/module/htmlformentry/widget/WidgetFactory.java

Added "&view=RAW_VIEW" in View link url
Replaced url parameter "view=download" by "download=true"
see https://issues.openmrs.org/browse/HTML-717

HTML-717: ComplexObsServlet to be used with RAW_VIEW.

---

omod/src/main/webapp/resources/htmlFormEntry.js

https://issues.openmrs.org/browse/HTML-731

HTML-731: Fixed htmlFormEntry.js numbers validation.

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/HtmlFormEntryGeneratorTest.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryGenerator.java

see https://issues.openmrs.org/browse/HTML-735

HTML-735: Repeat tag to allow extra space/line break before 'with' attr.

---

api/src/main/java/org/openmrs/module/htmlformentry/FormEntrySession.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormValidator.java
omod/src/main/java/org/openmrs/module/htmlformentry/web/controller/HtmlFormFromFileController.java
omod/src/main/resources/config.xml
omod/src/main/webapp/htmlFormFromFile.jsp

This prevents the load of files via absolute paths or path traversal.
see https://issues.openmrs.org/browse/HTML-730
- x ] I have **added tests** to cover my changes. (If you refactored
No? -> figure out why and add the fix to …

HTML-730: Do not allow loading arbitrary files

---

api-1.9/pom.xml
api-2.0/pom.xml
api-2.3/pom.xml
api-2.3/src/main/java/org/openmrs/module/htmlformentry/ConditionElement.java
api-2.3/src/main/java/org/openmrs/module/htmlformentry/handler/ConditionTagHandlerSupport2_3.java
api-2.3/src/test/java/org/openmrs/htmlformentry/element/ConditionElementTest.java
api-2.3/src/test/java/org/openmrs/htmlformentry/element/ConditionTagTest.java
api-tests/pom.xml
api/src/main/java/org/openmrs/module/htmlformentry/handler/ConditionTagHandler.java
api/src/main/java/org/openmrs/module/htmlformentry/handler/ConditionTagHandlerSupport1_10.java
api/src/main/resources/messages.properties
api/src/test/resources/org/openmrs/module/htmlformentry/include/RegressionTest-data-openmrs-2.30.xml
api/src/test/resources/org/openmrs/module/htmlformentry/include/conditionForm.xml
omod/pom.xml
pom.xml

Ticket: https://issues.openmrs.org/browse/HTML-725

HTML-725: <condition/> to support VIEW and EDIT modes.

---

api/src/main/java/org/openmrs/module/htmlformentry/element/EncounterDetailSubmissionElement.java
api/src/main/java/org/openmrs/module/htmlformentry/handler/EncounterLocationHandler.java
api/src/test/java/org/openmrs/module/htmlformentry/EncounterLocationTagTest.java
api/src/test/resources/org/openmrs/module/htmlformentry/include/encounterLocationTest.xml

Description
Added restrictToSupportedVisitLocations attribute to Encounter location tag
Ticket ID:
https://issues.openmrs.org/browse/HTML-713

HTML-713: New restrictToSupportedVisitLocations attribute to EncounterLocation tag

---

api-2.3/src/test/java/org/openmrs/htmlformentry/element/ConditionTagTest.java
api-tests/src/test/java/org/openmrs/module/htmlformentry/EnrollInProgramTagTest.java
api/src/main/java/org/openmrs/module/htmlformentry/FormEntrySession.java
api/src/main/java/org/openmrs/module/htmlformentry/FormSubmissionActions.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java
api/src/main/java/org/openmrs/module/htmlformentry/element/EnrollInProgramElement.java
api/src/main/java/org/openmrs/module/htmlformentry/handler/EncounterLocationHandler.java
api/src/test/resources/org/openmrs/module/htmlformentry/include/enrollPatientInProgramSimpleFormWithLocationTag.xml

HTML-681: enrollInProgram tag should set the location

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/EncounterLocationTagTest.java
api/src/main/java/org/openmrs/module/htmlformentry/FormEntryContext.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryConstants.java
api/src/main/java/org/openmrs/module/htmlformentry/element/EncounterDetailSubmissionElement.java
api/src/test/resources/org/openmrs/module/htmlformentry/data/RegressionTest-data-openmrs-2.1.xml
omod/src/main/resources/config.xml

HTML-752: Add new "restrictToCurrentVisitLocation" to EncounterLocation

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/handler/DrugOrderTagHandlerTest.java
api-tests/src/test/java/org/openmrs/module/htmlformentry/widget/DrugOrderWidgetTest.java
api/src/main/java/org/openmrs/module/htmlformentry/export/InitializerExportUtil.java
api/src/main/java/org/openmrs/module/htmlformentry/handler/DrugOrderTagHandler.java
api/src/main/java/org/openmrs/module/htmlformentry/schema/DrugOrderField.java
api/src/test/java/org/openmrs/module/htmlformentry/tester/FormSessionTester.java
api/src/test/resources/org/openmrs/module/htmlformentry/data/RegressionTest-data-openmrs-2.1.xml
api/src/test/resources/org/openmrs/module/htmlformentry/include/drugOrderTestFormAllDefaults.xml
api/src/test/resources/org/openmrs/module/htmlformentry/include/drugOrderTestFormLegacyDiscontinueReason.xml
api/src/test/resources/org/openmrs/module/htmlformentry/include/drugOrderTestFormLegacyNamesAndLabels.xml
api/src/test/resources/org/openmrs/module/htmlformentry/include/drugOrderTestFormOrderProperties.xml
api/src/test/resources/org/openmrs/module/htmlformentry/include/drugOrderTestFormV2Attributes.xml
omod/src/main/webapp/resources/drugOrderWidget.js

This adds additional unit tests (and some related fixes identified in the course of doing so) for the new drugOrder tag.

Drugorder tests

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/ObsTagTest.java
api/src/main/java/org/openmrs/module/htmlformentry/element/ObsSubmissionElement.java

HTML-769: Obs with Value Drug corrupts data upon edit

---

api/src/main/java/org/openmrs/module/htmlformentry/widget/OrderWidget.java
omod/src/main/webapp/resources/orderWidget.css
omod/src/main/webapp/resources/orderWidget.js

Ensure view of existing orders respects the configured template

---

api/src/main/java/org/openmrs/module/htmlformentry/handler/OrderTagHandler.java

HTML-774: Order Tag only displays displays one drug per formulation)

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/ObsAnswerLocationTagsTest.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java
api/src/main/java/org/openmrs/module/htmlformentry/element/EncounterDetailSubmissionElement.java
api/src/main/java/org/openmrs/module/htmlformentry/element/ObsSubmissionElement.java
api/src/test/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtilTest.java

HTML-775: Add "restrictToCurrentVisitLocation" attribute to Obs tag

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/element/ProviderRoleAndElementTest.java
api/src/main/java/org/openmrs/module/htmlformentry/tag/EncounterProviderAndRoleTag.java

Follow up commit for https://github.com/openmrs/openmrs-module-htmlformentry/pull/235
Ticket Id
https://issues.openmrs.org/browse/HTML-419
cc  @mogoodrich

Follow up commit for HTML-419

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtilTest.java
api-tests/src/test/java/org/openmrs/module/htmlformentry/ObsGroupTagTest.java
api/src/main/java/org/openmrs/module/htmlformentry/FormEntryContext.java
api/src/main/java/org/openmrs/module/htmlformentry/HtmlFormEntryUtil.java
api/src/main/java/org/openmrs/module/htmlformentry/action/ObsGroupAction.java
api/src/main/java/org/openmrs/module/htmlformentry/element/ObsSubmissionElement.java
api/src/main/java/org/openmrs/module/htmlformentry/handler/ObsGroupTagHandler.java
api/src/main/java/org/openmrs/module/htmlformentry/schema/ObsGroup.java
api/src/main/java/org/openmrs/module/htmlformentry/widget/ProviderWidget.java
api/src/test/resources/org/openmrs/module/htmlformentry/include/obsGroupWithHiddenObs.xml

https://issues.openmrs.org/browse/HTML-561
Rename context obs to hidden obs and change API a bit.
At Ellen's request, it is now like
```xml
<obsgroup groupingConceptId="CIEL:1727" hiddenConceptId="CIEL:1728" hiddenAnswerConceptId="PIH:ASTHMA">
```
Sorry some formatter stuff got thrown in there too.

HTML-561 Obs group support for Signs and Symptoms construct

---

omod/src/main/webapp/resources/htmlForm.js
omod/src/main/webapp/resources/htmlFormEntry.js

HTML-804: When/Then Display with Radio Button doesn't work if multiple buttons trigger same element
No? -> figure out why and add the fix to your commit. It is your responsibility to …

HTML-803: When/ThenDisplay doesn't work when radio button unselected

---

api/src/main/java/org/openmrs/module/htmlformentry/FormEntrySession.java

HTML-811: HFE should void all obs children when parent obs is voided

---

omod/src/main/webapp/resources/htmlForm.js

HTML-814: `controls`/`when` tag doesn't work with `answerConceptId`

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/ObsGroupTagTest.java
api/src/main/java/org/openmrs/module/htmlformentry/ObsGroupComponent.java
api/src/main/java/org/openmrs/module/htmlformentry/action/ObsGroupAction.java
api/src/main/java/org/openmrs/module/htmlformentry/handler/ObsGroupTagHandler.java
api/src/main/java/org/openmrs/module/htmlformentry/schema/ObsGroup.java
api/src/test/java/org/openmrs/module/htmlformentry/RegressionTestHelper.java

HTML-826: Obs Group Hidden Obs does not always get created

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/VelocityFunctionsTest.java
api/src/main/java/org/openmrs/module/htmlformentry/VelocityFunctions.java

HTML-827: Create "aMomentBefore" and "aMomentAfter" Velocity function

---

api/src/main/java/org/openmrs/module/htmlformentry/element/ObsSubmissionElement.java

see https://issues.openmrs.org/browse/HTML-832

HTML-832 - Correctly pass toggle attribute into checkbox for valueDrug.

---

api/src/main/java/org/openmrs/module/htmlformentry/FormEntrySession.java

@mseaton , the following change resolves the issue we had with the mental health form in PIH EMR. Please let me know if this looks OK to you? Thanks!

HTML-834, reset order dateActivated to match encounter datetime

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/ObsGroupTagTest.java
api/src/main/java/org/openmrs/module/htmlformentry/ObsGroupComponent.java
api/src/main/java/org/openmrs/module/htmlformentry/action/ObsGroupAction.java
api/src/main/java/org/openmrs/module/htmlformentry/handler/ObsGroupTagHandler.java
api/src/main/java/org/openmrs/module/htmlformentry/schema/ObsGroup.java
api/src/test/resources/org/openmrs/module/htmlformentry/include/obsGroupWithHiddenNumericObs.xml
api/src/test/resources/org/openmrs/module/htmlformentry/include/obsGroupWithHiddenTextObs.xml

see https://issues.openmrs.org/browse/HTML-850

HTML-850: Support Hidden Obs of type Text and Numeric

---

api-tests/src/test/java/org/openmrs/module/htmlformentry/RegressionTest.java
api/src/main/java/org/openmrs/module/htmlformentry/element/ObsSubmissionElement.java

see https://issues.openmrs.org/browse/HTML-854

HTML-854: allowFutureTimes should not allow times in the future

---

omod/src/main/java/org/openmrs/module/htmlformentry/web/controller/HtmlFormController.java

see https://issues.openmrs.org/browse/HTML-858

HTML-858 - Unescape submitted xml on htmlform admin page.

---

api/src/main/java/org/openmrs/module/htmlformentry/handler/OrderTagHandler.java
api/src/main/java/org/openmrs/module/htmlformentry/widget/OrderWidget.java
api/src/main/java/org/openmrs/module/htmlformentry/widget/OrderWidgetConfig.java
omod/src/main/webapp/resources/orderWidget.js

see https://issues.openmrs.org/browse/HTML-868

HTML-868 - Order widget should make drug ingredients available
